### PR TITLE
Fix categories

### LINKED ISSUE #930: Bug in categories displaying when coming back from the creating category screen
When selecting several categories, then trying to create a new one, only the first previously selected category stays displayed as added (even though the other are added on the file)
Furthemore, the newly created category is not added to the file

### PR DESCRIPTION
**Pull request by valentinperignon**
Fixes #930

### CODE REVIEW

File: kDrive/UI/Controller/Files/Categories/EditCategoryViewController.swift [hunk 1]
```diff
@@ -26,6 +26,7 @@ class EditCategoryViewController: UITableViewController {
     var category: kDriveCore.Category?
     /// The file to add the category to after creating it.
     var fileToAdd: File?
```
Comment (PhilippeWeidmann) [inline kDrive/UI/Controller/Files/Categories/EditCategoryViewController.swift:28]: Remove me

Comment (valentinperignon) [reply kDrive/UI/Controller/Files/Categories/EditCategoryViewController.swift]: You've been removed

**Review by Ambrdctr — APPROVED** [review]
