### PR TITLE
Fix back button

### LINKED ISSUE #564: Back button titles not showing on long-press
We should reestablish `backButtonItem` and use `backButtonDisplayMode = .minimal` everywhere in the app.

### PR DESCRIPTION
**Pull request by valentinperignon**
Closes #564

### CODE REVIEW

File: kDrive/Utils/UINavigationItem+Extension.swift [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+ GNU General Public License for more details.
+
+ You should have received a copy of the GNU General Public License
+ along with this program.  If not, see <http://www.gnu.org/licenses/>.
+ */
+
+import UIKit
+
+extension UINavigationItem {
+    func dontShowBackButtonText() {
```
Comment (PhilippeWeidmann) [inline kDrive/Utils/UINavigationItem+Extension.swift:22]: Rename "dontShow" to "hide":
- It improves code readability 
- It looks more like Apple's own style (eg. view.isHidden)

**Review by PhilippeWeidmann — CHANGES_REQUESTED** [review]
Rename "dontShow" to "hide":

It improves code readability
It looks more like Apple's own style (eg. view.isHidden)

**Review by PhilippeWeidmann — DISMISSED** [review]

**Review by flowbe — APPROVED** [review]

**Review by Lnamw — APPROVED** [review]
